### ISSUE TITLE
Help to install the challenges

### ISSUE THREAD

**Issue by jomagalo** [rkevin-arch/ECS189M#16]
Hi,
I am trying to install these challenges but can't find the way. After compiling with `sudo python3 ./build.py` the users are installed in the system and the challenges are compiled but the database is not affected, that is, the challenges do not appear in the website part.

I comment on the steps I have followed:

- I have installed the web application
- installed python3, Nuitka and Scons
- RUN `sudo python3 ./build.py`

**Comment by rkevin-arch** [comment]
Unfortunately the website uses its own database. Since this was a one-off thing, I basically entered everything manually into the website. I originally wanted to generate SQL commands from build.py using the `info.yml`s but eventually gave up on that idea. You can check https://photon.rkevin.dev for all the challenge descriptions, and if you want to I can dump my SQL database for you.

For SSHable challenges, `build.py` should have automatically created some user accounts on your system. Just do `sudo passwd [challengename]` to change their password, and allow SSH access to them.

For xinetd (nc/binary) challenges, go into `utils/xinetd` and do a `docker-compose build && docker-compose up`. Edit the `docker-compose.yml` file as you see fit if you aren't using ports `30001-30020`.

For webapp challenges, this is a bit complicated. The way I'm doing it is via beamsplitter, check `utils/beamsplitter/README.md` for more details, and `utils/beamsplitter/apache_rules` had some Apache rules I used to get the forwarding to work (you probably have to modify it for your own use). I can explain more if you have any questions.

**Comment by jomagalo** [comment]
Thank you very much for such a quick response. It would be perfect to have the database.

Greetings

**Comment by rkevin-arch** [comment]
Here's a dump of the `categories`, `challenges` and `files` tables of the database: https://gist.github.com/rkevin-arch/f637896b866c19f6c65fb83a184eab6d

Note that mellivora has its own place to upload files to, so you should also download [this tar file](https://rkevin.dev/upload.tar.gz) and extract its contents into whereever the mellivora writable volume is (if you are using my docker-compose file, it might be under `/var/lib/docker/volumes/mellivora_mellivorawritable/_data/upload`). Let me know when you are done so I can delete that file from my webserver. Alternatively, do not import the `files` table from my dump and just upload the files using the GUI manually. If you are making custom changes to the challenges, you should also modify the files (or delete them and reupload your own from the web interface).

I'm not the biggest fan of the mellivora scoreboard, but it's one of the quick-and-dirtiest solutions out there that doesn't require a load of resources (CTFd crashed my raspberry pi :/). I'm considering maybe writing my own custom solution for this, but it's very low priority for me right now (ECS189M is basically a finished project for me).

**Comment by jomagalo** [comment]
I already have the data. 

Thank you very much again

**Comment by rkevin-arch** [comment]
Cool, if you have any more questions or comments please let me know!
